### ISSUE TITLE
Publish guidelines on how to make contributions

### ISSUE THREAD

**Issue by ashishjain14** [WiproOpenSourcePractice/galaxia#30]
List down the steps which a new contributor needs to follow to make effective contributions

**Comment by deepthis594** [comment]
The basic steps involve:
1.Fork the repository and clone it locally. Refer links https://guides.github.com/activities/forking/  https://help.github.com/articles/syncing-a-fork/
2.Create a branch - creating an environment where you can try out your ideas. This will not affect master branch. Refer link https://guides.github.com/introduction/flow/
3.Open pull requests.Refer https://guides.github.com/activities/contributing-to-open-source/

**Comment by ashishjain14** [comment]
Deepthi,
Thanks for listing out steps, Can you update the same in our README file available at https://github.com/WiproOpenSourcePractice/galaxia/blob/master/README.md

You will have to follow the same steps as highlighted above. You can open a pull request and submit your patch for review. This will be a good start for starting contribution to galaxia.

Regards
Ashish

**Comment by ashishjain14** [comment]
We have got a section in the end
https://github.com/WiproOpenSourcePractice/galaxia/blob/master/README.md#contributing-to-galaxia

You can provide details there.

**Comment by ashishjain14** [comment]
Deepthi,

Thanks for the pull request, however I would prefer to have actual commands to be shown in the document rather than hyperlinks, bdre has done something similar have a look

https://github.com/WiproOpenSourcePractice/openbdre#how-to-contribute

**Comment by deepthis594** [comment]
Ashish,
 I have made the changes.Commands are shown in the document.Pull request is sent.Please review.

**Comment by ashishjain14** [comment]
Deepthi,

Applied the pull request. Thanks for your contribution.
