### ISSUE TITLE
Issue with galaxia command line option

### ISSUE THREAD

**Issue by krishnayeddula** [WiproOpenSourcePractice/galaxia#34]
This is a cosmetic issue with galaxia command line option
[Galaxia cmdline.txt](https://github.com/WiproOpenSourcePractice/galaxia/files/264469/Galaxia.cmdline.txt)
:

galaxia --help 
galaxia catalogue list --unit-type exporters
            List all created exporters

Error while issuing above command. However the working command line option is
galaxia catalogue list --unit-type exporter

Same issue seen with 
galaxia catalogue list --unit-type dashboards
The working command line option is: galaxia catalogue list --unit-type dashboard

**Comment by ashishjain14** [comment]
Fixed in Galaxia using commit 47e6e56a32efaf36e268bc5046c21a9225a7b6ef
Fixed in Galaxia client using commit 10eecd1e4c1c68aac9b52a3c5516379c5d59ebd9

**Comment by ashishjain14** [comment]
Vijay,
Can you verify if this has been fixed and help us in closing this issue.
Ashish

**Comment by krishnayeddula** [comment]
Ashish,
Sure i can verify this but do i need to run Ansible again to Install latest version of Galaxia which is having the fix? or do let me know the procedure.

Here is my current version:
krishnayeddula@ubuntu:~$ galaxia --version
galaxiaclient v1.0

Thanks,
Vijay

**Comment by ashishjain14** [comment]
Here is how you can test this out:

1) Pull the latest galaxia source code using git
2) Run the ansible role for galaxia.
3) Test the various commands which were an issue earlier.

**Comment by ashishjain14** [comment]
Issue has been fixed closing it.
